<?php

/**
 *        DO NOT EDIT THIS FILE EITHER!
 * 
 * Unless you've renamed it to [settings.inc], in which case it is recommended
 * that you do, in fact, edit the settings below.
 * 
 */


// Database connection information
$sql_connection_readonly = array(
    'username' => 'ldb_ro',
    'password' => 'change-me',
    'database' => 'ledendatabase'
);
$sql_connection_readwrite = array(
    'username' => 'ldb_rw',
    'password' => 'change-me-as-well',
    'database' => 'ledendatabase',
    'log file' => '/tmp/query_log'
);


