<?php

/*
    Copyright (C) 2011 Thijs van Dijk
    
    This file is part of CM-LDB.

    CM-LDB is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    CM-LDB is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with CM-LDB.  If not, see <http://www.gnu.org/licenses/>.
*/

/*
   These settings override the default settings.
*/

/**
 *        DO NOT EDIT THIS FILE EITHER!
 * 
 * Unless you've renamed it to [settings.inc], in which case it is recommended
 * that you do, in fact, edit the settings below.
 * 
 */


// Database connection information
$sql_connection_readonly = array(
    'username' => 'ldb_ro',
    'password' => 'change-me',
    'database' => 'ledendatabase'
);
$sql_connection_readwrite = array(
    'username' => 'ldb_rw',
    'password' => 'change-me-as-well',
    'database' => 'ledendatabase',
    'log file' => '/tmp/query_log'
);


// The default e-mail domain to authenticate against.
$default_domain = 'collegiummusicum.nl';


// Cryptographic key, used for digitally signing cookies.
$secret_key = <<<EOT
    This is a cryptographic key, used for digitally signing cookies.
    
    You should change the contents of this key to something different from the
    standard text.
    
    Preferably something long, and difficult to guess.
EOT;



// A watermark logo to add to all the envelope labels
$sticker_logo_file = 'img/logo-sticker.png';

